using UnityEngine;
using UnityEngine.SceneManagement;
public class MenuPrincipal : MonoBehaviour
{
  
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
    // M√©thode pour aller √† l'√©cran de connexion
    public void GoToLogin()
    {
        SceneManager.LoadScene("SignIn");
    }

    // M√©thode pour aller √† l'√©cran d'inscription
    public void GoToSignup()
    {
        SceneManager.LoadScene("SignUp");
    }
    
    public void GoToHowToPlay()
    {
        SceneManager.LoadScene("HowToPlay");
    }
    public void Play()
    {
        Debug.Log("Play LEVEL" + UserSession.CurrentUserLevel);
        Debug.Log("PREFS LEVEL" + PlayerPrefs.GetInt("UserLevel"));
        switch (UserSession.CurrentUserLevel)
        {
            case 0:
                SceneManager.LoadScene("Intro");
                break;
            case 1:
                SceneManager.LoadScene("Elec");
                break;
            case 2:
                SceneManager.LoadScene("Fire");
                break;
            case 3:
                SceneManager.LoadScene("Meca");
                break;
        }
       
    }
    
    // üõë Bouton D√©connexion : Effacer la session et revenir au menu principal
    public void Logout()
    {
        PlayerPrefs.DeleteKey("UserId");
        PlayerPrefs.DeleteKey("Username");
        PlayerPrefs.DeleteKey("UserLevel");
        PlayerPrefs.Save(); // Sauvegarde les changements

        Debug.Log("D√©connexion r√©ussie. Retour au menu principal.");
        SceneManager.LoadScene("SignIn"); // Redirige vers le menu principal
    }

    // ‚ùå Bouton Quitter : Fermer compl√®tement l'application
    public void QuitGame()
    {
        Logout();
        Debug.Log("Fermeture du jeu.");
        Application.Quit(); // Quitte le jeu (ne fonctionne pas dans l'√©diteur)

        // Permet de simuler la fermeture dans l'√©diteur Unity
        #if UNITY_EDITOR
                UnityEditor.EditorApplication.isPlaying = false;
        #endif
    }

    public void Historique()
    {
        SceneManager.LoadScene("Score"); 
    }
    
    public void LoadMenuPrincipal()
    {
        SceneManager.LoadScene("MenuPrincipal"); // Redirige vers le menu principal
    }
}
